### ISSUE TITLE
Roadmap to turn on rehydration by default

### ISSUE THREAD

**Issue by sdhull** [ember-fastboot/fastboot#214]
This is a list of things needed to be able to turn on rehydration by default.
**Primary objective:** turn on rehydration by default (and not have it produce weird/unexpected results in a majority of apps)
**Hurdles:**
 * rehydration markers rendered in tags that shouldn't have them
   * [ ] `<title>{{title}}</title>`
   * [ ] `<style>{{style}}</style>`
   * [ ] `<pre>{{pre}}</pre>`

What am I missing here?
